<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class financeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('finances')->insert([
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Tidak ada FPP yang oustanding',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Semua mutasi kas & bank ter-input sesuai nature transaksi',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Biaya >30 Juta dilakukan Amortisasi',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Pengakuan Aset Nilai >= 1 Juta, Low Value Aset <= 1 Juta',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Pembayaran invoice sesuai kelengkapan dokumen.',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Closing laporan keuangan tepat waktu',
                'target' => 'Berita Acara Cash & Stock Opname per, 30 akhir bulan',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Laporan Kas Harian',
                'target' => 'Laporan Kas Harian 183 --> mutasi pelunasan piutang',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Laporan Kas Harian',
                'target' => 'Laporan Kas Harian Surabaya --> saldo tetap 5 Juta per bulan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Laporan Kas Harian',
                'target' => 'Laporan Kas Harian Pasuruan --> saldo tetap 5 Juta per bulan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Laporan Kas Harian',
                'target' => 'Laporan Kas Harian Jakarta     --> saldo tetap 3 Juta per bulan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Laporan Kas Harian',
                'target' => 'Laporan Kas Harian Bali           --> saldo tetap 2 Juta per bulan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Pajak dibayarkan, saat invoice dicadangkan untuk dibayarkan',
                'janw1' => 'OK',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Penerbitan e-bukpot saat invoice dicadangkan untuk dibayarkan',
                'janw1' => '',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Pembayaran pajak PPh 21, Unifikasi & Angsuran PPh badan maks. Tgl 10 bulan berikutnya',
                'janw1' => 'OK',
                'janw2' => '',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Pelaporan PPh maks. Tgl 20 bulan berikutnya',
                'janw1' => '',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Pengajuan kurang bayar PPN masa maks. Tgl 27 bulan berikutnya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Perpajakan',
                'target' => 'Pelaporan PPN masa maks. 30 bulan berikutnya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Setting laporan penjualan setiap bulan maks. Tgl 27 bulan berikutnya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Rekonsiliasi Hutang Pajak PPH & PPN vs SPT PPH Unifikasi',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Rekonsiliasi PPh 21 antara Laporan Keuangan VS SPT PPh 21',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Rekonsiliasi Omset VS SPT PPN',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Uji Arus Piutang antara GL Piutang, Kas Bank Masuk vs PPN Out yang dilaporkan di SPT PPN Masa',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Setting Summary Stock sesuai laporan penjualan fiskal',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Laporan Kas Harian sesuai laporan penjualan fiskal',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Daftar Aktiva Tetap Fiskal',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Kartu Hutang Fiskal',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Kartu Piutang Fiskal',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Laporan Keuangan Fiskal',
                'target' => 'Setting Laporan Harian Kas 183',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Budget vs Actual',
                'target' => '1. Monitoring Budget vs Actual secara monthly dan yearly
                             2. Monthly Actual Cost Lebih Besar dari Budget, maka FPP direject dan diminta untuk pembetulan budget dan tanda tangan Direksi.',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain HPP per SKU',
                'target' => 'Laporan Hasil Produksi per tanggal 26 bulan berikutnya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain HPP per SKU',
                'target' => 'Rekap Master detail standar cost komponen HPP per SKU',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain HPP per SKU',
                'target' => 'Alokasi biaya actual per komponen HPP',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain HPP per SKU',
                'target' => 'Analisa Selisih Efisien dan Inefisien per komponen HPP',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain HPP per SKU',
                'target' => 'Analisa Batch Produksi - Standar vs Actual',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Pengajuan Pembayaran FPP',
                'target' => '1. Kelengkapan dokumen FPP yaitu :
                                - FPP & PRF ditanda tangan oleh semua Pihak Terkait
                                - Surat Penawaran Harga
                                - PO (Purchase Order) harus ada tanda tangan Direksi
                                - Proforma Invoice
                                - Invoice
                                - Faktur Pajak
                                - Surat Jalan
                                - Print email terkait (jika ada)',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Pengajuan Pembayaran FPP',
                'target' => '2. FPP diajukan jika tagihan sudah mendekati Jatuh Tempo',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Maintain Pengajuan Pembayaran FPP',
                'target' => '3. FPP yang akan diajukan pembayaran sesuai kebutuhan perusahaan saat itu',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Kas Bon',
                'target' => '1. Kas Bon harus diselesaikan di hari yang sama, maksimal 1 hari.',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Kas Bon',
                'target' => '2. Kas Bon akan diberikan jika tidak ada kas bon yang outstanding.',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Kas Bon',
                'target' => '3. User menulis form kas bon dan di approval oleh Lead Departemen nya.',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Kas Bon',
                'target' => '4. Nilai kas bon yang disetujui <= 1 Juta',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Menjaga Rasio EBIT 20%',
                'renker' => 'Kas Bon',
                'target' => '5. Jika User tidak melakukan penyelesaian atas kas bon nya sebelum closing laporan keuangan, maka diajukan sebagai Piutang Karyawan & Potong Gaji.',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'List kewajiban perpajakan PT LSI, PT ABA, PT GII & CV ABA',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'Monitoring status PKP dan atau Non PKP',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'Time Line untuk pembayaran dan pelaporan perpajakan',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'Cek terkait administrasi pelaporan keuangan nya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'Maintain setiap ada STP, SKPKB, SP2DK dan lainnya',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Tax Planning',
                'renker' => 'Mitigasi resiko perpajakan',
                'target' => 'Menjalin komunikasi dengan AR dan team pemeriksa pajak',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Memastikan semua PO & Invoice diterbitkan dihari yang sama',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Memastikan DO terkirim',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Input pelunasan piutang setiap harinya',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Buat bukti kas dan bank masuk atas pelunasan piutang',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Koordinasi dengan team sales terkait pelunasan piutang yang tidak diketahui nama pelanggan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Mengatur umur piutang per customer dan koordinasi dengan team sales',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Umur Piutang > 60 hari langsung koordinasi dengan team sales untuk dilakukan penagihan',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Piutang Usaha',
                'renker' => 'Maintain Piutang dan Penjualan',
                'target' => 'Update penjualan ke Direksi per chanel per sales diakhir hari',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Hutang Usaha',
                'renker' => 'Maintain Hutang dan Pembayaran',
                'target' => 'Memastikan tidak ada invoice yang outstanding / belum ter-input di program',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Hutang Usaha',
                'renker' => 'Maintan Hutang dan Pembayaran',
                'target' => 'Koordinasi dengan admin produksi terkait penerimaan barang atas invoice outstanding lebih dari 30 hari',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Hutang Usaha',
                'renker' => 'Maintain Hutang dan Pembayaran',
                'target' => 'Mapping jadwal pembayaran per vendor per invoice',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Hutang Usaha',
                'renker' => 'Maintain Hutang dan Pembayaran',
                'target' => 'Mengatur umur hutang usaha per vendor dan koordinasi dengan team Purchase',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Hutang Usaha',
                'renker' => 'Maintain Hutang dan Pembayaran',
                'target' => 'Umur Hutang > 360 hari koordinasi dengan accounting dan purchase untuk dilakukan write off',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => 'OK',
                'janw4' => 'OK',
            ],


        ]);
    }
}
