<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class protechSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mts')->insert([
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Forecast BM & PB ditahun 2025	142.342	kg',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Kebutuhan tenaga kerja line cookies /day	24org',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Hasil produksi /day	912	kg /day',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Kebutuhan hari kerja untuk menyelesaikan total forecast	156Hk',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Value total tenaga kerja Rp 120.000	Rp449.280.000=155 HK',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Energy Listrik (Rp 757.216 /day) CNG (Rp 814.530 /day) Total Rp 1.571.746	Rp245.192.376/Tahun',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Output naik 2x dari 912 Kg menjadi 1824 Kg /day	1.824kg /day',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Tenaga Kerja	24/opr',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Jumlah HK	78Hari kerja',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Total Biaya Tenaga Kerja (Rp 120.000)	Rp224.750.526	78 HK',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Nilai Energy Listrik (Rp 757.216 /day) CNG (Rp 814.530 /day) Total Rp 1.571.746	Rp122.656.507/Tahun',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Nilai Efisiensi Tenaga Kerja	Rp224.529.474	',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Nilai Efisiensi Energy listrik dan gas CNG	Rp122.535.869	',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'Penambahan Oven Pengering Rotary dan Trolley',
                'target' => 'Total nilai Efisiensi yang akan didapatkan sebesar	Rp347.065.342	/tahun',
                'janw1' => 'OK',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Jumlah operational mesin dalam 1 bulan	480	jam /bulan',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Target downtime	5%	/bulan',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BM & PB 2x lipat dari kapasitas Tahun 2024',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Maximal Jam downtime	24	jam /bulan',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BT & CT dari 7.500 pcs /day menjadi 12.000 pcs /day',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Jumlah operational mesin dalam 1 bulan	480	jam /bulan',
                'janw1' => '',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BT & CT dari 7.500 pcs /day menjadi 12.000 pcs /day',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Target downtime	5%	/bulan',
                'janw1' => '',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningakatan kapasitas produksi cookies BT & CT dari 7.500 pcs /day menjadi 12.000 pcs /day',
                'renker' => 'prefentive maintenance, overhoul, general cleaning, general cek up, inspeksi part, dan improvement mesin',
                'target' => 'Maximal Jam downtime	24	jam /bulan',
                'janw1' => '',
                'janw2' => 'OK',
                'janw3' => '',
                'janw4' => '',
            ],
            [
                'proker' => 'Peningkatan skill tenaga kerja operator',
                'renker' => 'Training Produktivitas kepada tenaga kerja produksi',
                'target' => 'Meningkatkan target produksi dan meningkatkan performa kerja',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Peningkatan skill tenaga kerja operator',
                'renker' => 'Training sop dan ik mesin kepada tenaga kerja operator',
                'target' => 'Meningkatkan pengetahuan operator dan meningkatkan performa kerja',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],
            [
                'proker' => 'Peningkatan skill tenaga kerja operator',
                'renker' => 'Training GMP',
                'target' => 'Meningkatkan pengetahuan operator dan meningkatkan performa kerja',
                'janw1' => '',
                'janw2' => '',
                'janw3' => '',
                'janw4' => 'OK',
            ],

        ]);
    }
}
